FROM python:3.8-slim
EXPOSE 80

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

# RUN /bin/sh -c python3 manage.py makemigrations video

# RUN /bin/sh -c python3 manage.py migrate video

# RUN /bin/sh -c python3 manage.py migrate

CMD ["python3" , "manage.py", "runserver","0.0.0.0:80"]

